---
- hosts: users

  tasks:
    - name: define experiment
      file:
        state: touch
        path: /tmp/def-xpt

    - name: launch experiment
      file:
        state: touch
        path: /tmp/launch-xpt
