---
- hosts: users
  become: true

  tasks:
    - name: define experiment
      shell: su adama -c "./define_two.sh"
      args:
        chdir: /tmp/config

    - name: launch experiment
      shell: su adama -c "./run_two.sh"
      args:
        chdir: /tmp/config
