---
- hosts: all
  become: true

  tasks:
    - name: nuke tftpboot
      shell: rm -rf /tftpboot/*
    
    - name: init tftpboot proj dir
      file:
        path: /tftpboot/proj
        state: directory
        mode: 0755

    - name: copy syslinux core binary
      copy:
        dest: /tftpboot/lpxelinux.0
        src: /opt/deter/deterboot/bios/core/lpxelinux.0
        remote_src: True

    - name: copy syslinux modules
      shell: find /opt/deter/deterboot/bios -name *.c32 -exec cp "{}" /tftpboot/ \;

    - name: create pxelinux directory
      file: 
        path: /tftpboot/pxelinux.cfg
        state: directory
        mode: 0755

    - name: copy default pxelinux config
      copy:
        src: /tmp/config/pxelinux-default
        dest: /tftpboot/pxelinux.cfg/default
        remote_src: True


    - name: copy linux-mfs kernel
      copy:
        dest: /usr/testbed/www/linux-mfs/bzImage
        src: /opt/deter/linux-mfs/images/bzImage
        remote_src: True
    
    - name: copy linux-mfs rootfs
      copy:
        dest: /usr/testbed/www/linux-mfs/rootfs.cpio
        src: /opt/deter/linux-mfs/images/rootfs.cpio
        remote_src: True

    - name: update mfs keys
      command:  /tmp/config/update-mfs-keys.sh

