---
- hosts: all
  become: true

  tasks:

    - name: install software
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - lldpd
        - python3-pip
        - ansible
        - sshpass
        - bash-completion
        - vim
        - tmux
        - git
        - golang

    - name: bring up eth1
      command: ip link set up dev eth1

    - name: Setup network
      command: "{{ item }}"
      ignore_errors: yes
      no_log: true
      with_items:
        - ip link set up dev eth1
        - ip addr add 192.168.253.240/24 dev eth1
        - ip route add 192.168.0.0/24 via 192.168.253.254
        - ip route add 192.168.1.0/24 via 192.168.253.254
        - ip route add 192.168.2.0/24 via 192.168.253.254
        - ip route add 192.168.252.0/24 via 192.168.253.254
        - ip route add 192.168.253.0/24 via 192.168.253.254

