---
- hosts: all
  become: true

  tasks:
    
    - name: copy configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=True
      with_items:
        - { src: '/tmp/config/rc.conf', dest: '/etc/rc.conf' }
    
    - name: Bring up network
      command:  "{{ item }}"
      ignore_errors: yes
      with_items: 
        - /etc/rc.d/netif restart vtnet1
        - /etc/rc.d/netif restart vtnet1.2002
        - /etc/rc.d/netif restart vtnet1.2005
        - /etc/rc.d/routing restart
        - service dhclient restart vtnet0
        # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # /etc/rc.d/routing restart is a jackass, it clobbers dhcp routes but 
        # does not bother to put them back, so we need to restart dhclient to 
        # get them back ourselves
    
    - name: install software
      package:
        name: "{{ item }}"
        state: present
        use: pkgng
      with_items:
        - lldpd
        - go
        - git
    
    - name: Prep filesystem
      command:  "{{ item }}"
      with_items: 
        - mkdir -p /users /proj /groups /share

    - name: Safeguard rvn key
      command: "{{ item }}"
      with_items:
        - mkdir -p /etc/ssh/external_keys/rvn
        - cp /usr/home/rvn/.ssh/authorized_keys /etc/ssh/external_keys/rvn
    
    - name: Make testbed directory
      file:
        path: /usr/testbed
        state: directory

    - name: Link testbed source
      file:
        src: /opt/deter/testbed
        dest: /usr/testbed/src
        state: link

    - name: Softlink legacy perl location
      file:
        src: /usr/local/bin/perl
        dest: /usr/bin/perl
        state: link

    - name: Start lldpd
      service:
        name: lldpd
        state: restarted

