---
- hosts: all
  become: true

  vars:
    objdir: /usr/testbed/obj 
    srcdir: /usr/testbed/src
    mirror: mirror.deterlab.net
    tbdir: "{{ lookup('env', 'TBDIR') }}" 

  tasks:

    - name: Building and installing testbed
      command: /tmp/config/build_install.sh

    #this has to be done b/c for some reason calling the ansible that is
    #running on fbsd from a linux host ansible that is presumably a different
    #version fails
    - name: Running post install tasks
      include: "{{tbdir}}/install/boss_post_install_tasks.yml"

    - name: setting up api
      include: "{{tbdir}}/core/api/setup_tasks.yml"

    - name: installing api
      include: "{{tbdir}}/core/api/install_tasks.yml"
